### ISSUE TITLE
can't install in MacOS

### ISSUE THREAD

**Issue by yukimori** [jubatus/embedded-jubatus-python#15]
I tried to install embedded_jubatus in MacOS, but it is failed.

/usr/local/include/jubatus/core/storage/abstract_column.hpp:468:26: error: use of overloaded operator '!=' is ambiguous (with operand types 'const jubatus::util::lang::shared_ptr<abstract_column_base>' and 'long')

my environment:
OS X El Capitan
clang:4.2.1

**Comment by yukimori** [comment]
workaround
set environment variable when installed
CFLAGS=-std=c++11 pip install embedded_jubatus

**Comment by kmaehashi** [comment]
Fixed via #16 (I forgot to close this)
