### ISSUE TITLE
can't install on {anaconda3, miniconda3}

### ISSUE THREAD

**Issue by yukimori** [jubatus/embedded-jubatus-python#23]
can't install on {anaconda3, miniconda3}

mac OS X El Capitan(10.11.5)
with pyenv 1.0.0

OK:
2.7.11
3.5.1

NG:
anaconda3-4.1.0
miniconda3-4.0.5

error log:
$ CFLAGS=-std=c++11 pip install embedded_jubatus
...
/usr/bin/clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c++11 -I/Users/yukimori/.pyenv/versions/miniconda3-4.0.5/include/python3.5m -c src/embedded_jubatus.cpp -o build/temp.macosx-10.6-x86_64-3.5/src/embedded_jubatus.o
    In file included from src/embedded_jubatus.cpp:438:
    In file included from src/_wrapper.h:4:
    In file included from /usr/local/Cellar/jubatus-core/1.0.0-p1/include/jubatus/util/text/json.h:35:
    In file included from /usr/local/Cellar/jubatus-core/1.0.0-p1/include/jubatus/util/text/json/base.h:48:
    /usr/local/Cellar/jubatus-core/1.0.0-p1/include/jubatus/util/text/json/../../data/unordered_map.h:40:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

**Comment by kazuki** [comment]
please use clang++ instead of clang.
(I can't tested because I don't have macOS)

```
$ CXX=clang++ CXXFLAGS=-std=c++11 pip install embedded_jubatus
```

**Comment by yukimori** [comment]
Thank for your comment!

I tried:

```
$ CXX=clang++ CXXFLAGS=-std=c++11 pip install embedded_jubatus
```

but it's failed. I saw same error

**Comment by kmaehashi** [comment]
I tried with anaconda3-4.1.0 on pyenv and got the same result.
``CXX`` did not work; strangely, python uses ``CC`` to build it.
