### ISSUE TITLE
Implement missing common methods

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/embedded-jubatus-python#31]
As documented in README, currently the following common methods are not implemented in embedded-jubatus: ``get_status``, ``get_proxy_status``, ``do_mix``, ``get_name``, ``set_name`` and ``get_client``.
It is better to implement them so that users can share the same code as RPC version.

My idea:

* ``get_status``, ``get_proxy_status``: return the limited subset of status values
* ``do_mix``: do nothing and always return True
* ``get_name``: always return empty string
* ``set_name``: raise exception (in this case users expects to switch the model but it is not possible) 
* ``get_client``: return some object that behaves like client

**Comment by rimms** [comment]
We implemented the following methods:
* do_mix
* get_name
* set_name

I divide this issue to #53 and #54.
