### ISSUE TITLE
What Python versions supported?

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/embedded-jubatus-python#8]
Which Python version supported by this module?
Are there any python version-specific dependencies used?

cc: @kazuki

**Comment by kazuki** [comment]
The current implementation has been tested with the following versions of Python and doesn't use python version-specific features.
* 2.6 (TravicCI CentOS6)
* 2.7 (TravicCI CentOS7, Ubuntu)
* 3.4 / 3.5 (my env)

#9 is ok

**Comment by kmaehashi** [comment]
Thanks!
